name: mustafacv
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.2.2
  rive: ^0.13.0
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  firebase_storage: ^11.6.10
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/image/
